name: taskbit
description: A new Flutter project.

repository: https://github.com/XxThunderBlastxX/taskbit

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  go_router: ^9.0.3
  flutter_riverpod: ^2.3.6
  appwrite: ^9.0.1
  logger: ^1.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.2.0
  flutter_screenutil: ^5.8.4
  random_avatar: ^0.0.8
  uuid: ^3.0.7
  intl: ^0.18.1
  envied: ^0.3.0+3
  flutter_animate: ^4.2.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  envied_generator: ^0.3.0+3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env